### ISSUE TITLE
My organization repositories don't show up

### ISSUE THREAD

**Issue by adriaanvanrossum** [marmelab/sedy#67] opened 2017-02-28 17:13 UTC
### Description

My organisation repositories don't show up

### Steps to Reproduce

1. Go to https://marmelab.com/sedy
1. Click on "Authorize on Private & Public Repositories"
1. Grant access to organization repositories
1. Back on https://marmelab.com/sedy it shows only my personal repositories

**Expected behavior:** That I could select the organization repositories where I'm the owner

**Actual behavior:** Could only select my personal repositories

**Comment by Kmaschta** [comment] 2017-02-28 17:23
Yup, it's not supported yet.
But keep in touch, we'll switch to Github Integration soon and it'll allow us to support organisations.

**Comment by Kmaschta** [comment] 2017-03-06 17:06
Depends on https://github.com/marmelab/sedy/pull/73

**Comment by YPCrumble** [comment] 2017-07-10 12:30
@Kmaschta thanks for building Sedy! I'm very excited to be able to use this on my organization repos. I've configured it to work on my organization but still experiencing a couple issues - and the bot isn't showing up yet.

First, when I save Sedy to work for "All repositories" it appears that the setting doesn't get saved - it doesn't show a list of all repos and after I click save it shows a blank form. Is that expected behavior?

Second, I added Sedy to my organization, and tried activating for all repos and just one specific repo. I've done that, but when I comment on the code in a PR nothing happens. That's my main use case - commenting on changed code in a PR. Is there something I might be doing that would make Sedy integration not work?

I had installed the old version of Sedy before - perhaps I need to completely remove and reinstall? Will try that now...

Thanks again for building Sedy! I'd be happy to submit a PR for bugfixes/features if there's some way I can be helpful in solving these issues.

**Comment by Kmaschta** [comment] 2017-07-10 16:10
Hi @YPCrumble, thank you for your message.

1. I just checked, and you're right! The form seems weird, but when I go the my repo settings `https://github.com/[user]/[repo]/settings/installations` Sedy is correctly installed.

2. Can you provide me the exact date and time of your comment ? I'll be able to find the logs and debug if needed.

3. Again, you're right. Remove all webhooks and `sedy-bot` collaborators, their are no longer needed. Just go on this link and follow the instructions: https://github.com/apps/sedy

This issue is out-dated since [Sedy is a GitHub app](https://github.com/marmelab/sedy/pull/73). I close it.
Feel free to open a new issue!

**Closed by Kmaschta** 2017-07-10 16:10 UTC
Labels: enhancement

**Comment by YPCrumble** [comment] 2017-07-10 17:33
@Kmaschta thanks! The comment was posted by user "Youth1" at 2017-07-10T12:33:03Z (8:33AM EDT). 

I tried reinstalling Sedy but that didn't end up working. Thanks for any help!

**Comment by Kmaschta** [comment] 2017-07-11 15:41
@YPCrumble I found your request and I confirm you it's a bug!
It is related to https://github.com/marmelab/sedy/issues/79

I struggle to find how the `position` parameter works. If you have any clue, you can help me on the issue #79
